### ISSUE TITLE
question: why np.concatenate is not called in solve_foreground_background.py ?

### ISSUE THREAD

**Issue by wyshmily** [MarcoForte/closed-form-matting#16]
I see this code line is called when --solve-fg is setted
![image](https://user-images.githubusercontent.com/18300550/53148505-caefb200-35e5-11e9-9975-4dfd5ad907c3.png)

But in solve_foreground_background.py there is not.
![image](https://user-images.githubusercontent.com/18300550/53148409-8f54e800-35e5-11e9-8dfc-72e7f4c50a1c.png)

Just confused why is that?

**Comment by merofeev** [comment]
I think there is no any great idea behind this.

In the first case we concatenate foreground with alpha to output RGBA image that will be nicely displayed in most of image viewers and can be easily composed on the new background with almost any image editor.

Since solving for foreground with known alpha is very specific usecase, I made an assumption that user knows what he/she wants to do with foreground and background so we can just output raw data. Probably, it was bad design decision.

I think PR adding `--rgba` output option to `solve_foreground_background.py` and keeping `--foreground` and `--background` outputs intact is warmly welcome. I hope @MarcoForte will agree with me.

**Comment by wyshmily** [comment]
@merofeev Thank you very much.

I am working on developing a tool (for windows) with the "intelligent image cut out" functionality, and the cut out calculation should take place in the client side.

I use this code and found it a bit slow without gpu acceleration, even if I zoom in the image to about 200 pixels.

Can you provide some suggestion?

**Comment by merofeev** [comment]
> Can you provide some suggestion?

In your case I would try two things:
1. Don't use solve_foreground in interactive mode and just use it for final pass. In interactive mode use original image instead of estimated foreground image. In many cases solving for foreground gives just a minor barely noticeable improvement, so it can be omitted. 
2. Apply solve_foreground to downscaled image to save some computational time.

**Comment by wyshmily** [comment]
@merofeev Thanks a lot !
